### ISSUE TITLE
Force new users to confirm their emails

### ISSUE THREAD

**Issue by J3RN** [J3RN/time-tracker#119]
Reviewing the user accounts, it appears that many accounts use fictitious email addresses (e.g. example@example.com). In order to reduce (or possibly eliminate) the number of fictitious email addresses specified, we should have new users confirm their addresses before activating their accounts.

I believe that the best way to do this would be to use Devise's [confirmable module](https://github.com/plataformatec/devise/wiki/How-To:-Add-:confirmable-to-Users).

**Comment by 3ygun** [comment]
😢 it's for the best
