### ISSUE TITLE
Bootstrap modal new/edit forms 

### ISSUE THREAD

**Issue by J3RN** [J3RN/time-tracker#81]
Spiritual successor to #74 

I would like the new/edit forms found throughout the website to be implemented as [Bootstrap modals](http://getbootstrap.com/javascript/#modals) on the index pages (Tasks#index would hold the Tasks#new and Tasks#edit forms, etc). Naturally, I think it would be best to have these fields appear in a column with a save button at the bottom, much like the [Bootstrap static example](http://getbootstrap.com/javascript/#static-example).

I think using `render` and keeping the forms in their respective partials would work well, but I'm open to alternate implementations.

**Comment by rishiraj824** [comment]
on it @J3RN

**Comment by J3RN** [comment]
@rishiraj824 Any progress on this?

**Comment by rishiraj824** [comment]
Will be done today. Been travelling. @J3RN

**Comment by J3RN** [comment]
@rishiraj824 Now that Hacktoberfest is over, do you still want to work on this, or should I reassign it?

**Comment by J3RN** [comment]
I'm closing this in favor of using a fat client JavaScript frontend to somehow do creation of new tasks, tags, time entries, etc, inline.
